#!/bin/bash
sudo add-apt-repository -y ppa:webupd8team/java
sudo apt-get update
echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections
sudo apt-get -y install oracle-java8-installer 
java -version 
wget https://s3-us-west-2.amazonaws.com/dynamodb-local/dynamodb_local_latest.tar.gz
tar xfz dynamodb_local_latest.tar.gz
java -Djava.library.path=./DynamoDBLocal_lib -jar DynamoDBLocal.jar -sharedDb -inMemory &
sudo apt-get install php libapache2-mod-php7.0 unzip -y
curl -sS https://getcomposer.org/installer | php
php composer.phar require aws/aws-sdk-php	 
sudo apt-get install apache2 -y
sudo service apache2 start
sudo apt-get install awscli -y
aws configure
